### ISSUE TITLE
Buildに失敗する

### ISSUE THREAD

**Issue by a-ichikura** [jsk-ros-pkg/jsk_recognition#2660]
spotkinovaのwsでjsk_perceptionをbuildしようとしましたが、Failedになります。

```bash
eus@ubuntu:~/spotkinova_ws/src$ wstool 
workspace: /home/leus/spotkinova_ws/src

 Localname                   S SCM Version (Spec) UID  (Spec)  URI  (Spec) [http(s)://...]
 ---------                   - --- -------------- -----------  ---------------------------
 tork-a/visualization_rwt      git kinetic-devel  9c015164e95e github.com/tork-a/visualization_rwt.git
 tork-a/roswww                 git fetch15        fcb215a9331a github.com/knorth55/roswww.git
 spot-ros                      git develop/spot   21c2e0bd7384 github.com/sktometometo/spot_ros.git
 ros_kortex_vision             git master         e65349f08be7 github.com/Kinovarobotics/ros_kortex_vision
 ros_kortex                    git melodic-devel  1f9d60ae3e6e github.com/kinovarobotics/ros_kortex
 knorth55/app_manager_utils    git master         4d32e427220f github.com/knorth55/app_manager_utils.git
 jsk-ros-pkg/jsk_robot       M git develop/spot   9e59b7d50f0c github.com/sktometometo/jsk_robot.git
 jsk-ros-pkg/jsk_recognition M git master         be6e319d2979 github.com/jsk-ros-pkg/jsk_recognition.git
 jsk-ros-pkg/jsk_demos         git develop/spot   9f2765db099d github.com/sktometometo/jsk_demos.git
 jsk-ros-pkg/jsk_common        git develop/spot   ea3f9ceb7a03 github.com/sktometometo/jsk_common.git
 jsk-ros-pkg/jsk_3rdparty      git develop/spot   be0570485d7d github.com/sktometometo/jsk_3rdparty.git
 aerial_robot                  git develop/spot   c7f246236a0b github.com/sktometometo/aerial_robot.git
 PR2/app_manager               git kinetic-devel  9ed2f9254d3c github.com/PR2/app_manager.git
```

```bash
___________________________________________________________________________________________________________________________________________________________________________________________________________
Errors     << jsk_perception:make /home/leus/spotkinova_ws/logs/jsk_perception/build.make.001.log                                                                                                          
Please install CuPy

    sudo pip install cupy-cuda[your cuda version]
i.e.
    sudo pip install cupy-cuda91


/usr/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
[/home/leus/spotkinova_ws/src/jsk-ros-pkg/jsk_recognition/jsk_perception/sample/data/2016-11-11-12-53-06_in_lab.bag] File exists or not writable, so skipping creating symlink.
[/home/leus/spotkinova_ws/src/jsk-ros-pkg/jsk_recognition/jsk_perception/sample/data/2016-10-15-23-21-42_moving_bottle.bag] File exists or not writable, so skipping creating symlink.
[/home/leus/spotkinova_ws/src/jsk-ros-pkg/jsk_recognition/jsk_perception/sample/data/2020-11-11-15-58-47-d435-floor.bag] File exists or not writable, so skipping creating symlink.
[/home/leus/spotkinova_ws/src/jsk-ros-pkg/jsk_recognition/jsk_perception/sample/data/sample_mask_rcnn_73b2_kitchen.bag] File exists or not writable, so skipping creating symlink.
[/home/leus/spotkinova_ws/src/jsk-ros-pkg/jsk_recognition/jsk_perception/sample/data/sample_mask_rcnn_73b2_kitchen_japanese_label.bag] File exists or not writable, so skipping creating symlink.
CMakeFiles/jsk_perception.dir/src/bing.cpp.o: 関数 `jsk_perception::Bing::onInit()' 内:
/home/leus/spotkinova_ws/src/jsk-ros-pkg/jsk_recognition/jsk_perception/src/bing.cpp:89: `cv::saliency::ObjectnessBING::setTrainingPath(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' に対する定義されていない参照です
collect2: error: ld returned 1 exit status
make[2]: *** [/home/leus/spotkinova_ws/devel/.private/jsk_perception/lib/libjsk_perception.so] Error 1
make[1]: *** [CMakeFiles/jsk_perception.dir/all] Error 2
make[1]: *** 未完了のジョブを待っています....
make: *** [all] Error 2
cd /home/leus/spotkinova_ws/build/jsk_perception; catkin build --get-env jsk_perception | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...........................................................................................................................................................................................................
Failed     << jsk_perception:make                  [ Exited with code 2 ]                                                                                                                                  
Failed    <<< jsk_perception                       [ 25.4 seconds ]                                                                                                                                        
[build] Summary: 12 of 13 packages succeeded.                                                                                                                                                              
[build]   Ignored:   157 packages were skipped or are blacklisted.                                                                                                                                         
[build]   Warnings:  None.                                                                                                                                                                                 
[build]   Abandoned: None.                                                                                                                                                                                 
[build]   Failed:    1 packages failed.                                                                                                                                                                    
[build] Runtime: 29.0 seconds total. 
```

@sktometometo とbuildしていたのですが、詳しい原因がわからず現状jsk_pcl_rosだけ別でbuildしました。

**Comment by a-ichikura** [comment]
@sktometometo です。手元で同様のworkspaceを再現するために, vcstoolでワークスペース構成を出力しました。

```yaml
repositories:
  PR2/app_manager:
    type: git
    url: https://github.com/PR2/app_manager.git
    version: 9ed2f9254d3c5c81ee99a7eecab40a93174b71d6
  aerial_robot:
    type: git
    url: https://github.com/sktometometo/aerial_robot.git
    version: c7f246236a0b908ba0467f5e25022d0f04a96435
  jsk-ros-pkg/jsk_3rdparty:
    type: git
    url: https://github.com/sktometometo/jsk_3rdparty.git
    version: be0570485d7d92e39273bbad7a3137eccb23b8f4
  jsk-ros-pkg/jsk_common:
    type: git
    url: https://github.com/sktometometo/jsk_common.git
    version: ea3f9ceb7a030bf0e37460a08fba0f419aa13318
  jsk-ros-pkg/jsk_demos:
    type: git
    url: https://github.com/sktometometo/jsk_demos.git
    version: 9f2765db099d6028672549f23665d63f731daf3c
  jsk-ros-pkg/jsk_recognition:
    type: git
    url: https://github.com/jsk-ros-pkg/jsk_recognition.git
    version: be6e319d29797bafb10c589fdff364c3d333a605
  jsk-ros-pkg/jsk_robot:
    type: git
    url: https://github.com/sktometometo/jsk_robot.git
    version: 9e59b7d50f0c204fa787ce976b925545b05ef6e5
  knorth55/app_manager_utils:
    type: git
    url: https://github.com/knorth55/app_manager_utils.git
    version: 4d32e427220f0ec58c7c8cff706ad80cffc28ef5
  ros_kortex:
    type: git
    url: https://github.com/kinovarobotics/ros_kortex
    version: 1f9d60ae3e6e12a332f96678d18e496d365f20ea
  ros_kortex_vision:
    type: git
    url: https://github.com/Kinovarobotics/ros_kortex_vision
    version: e65349f08be77f3f4b4ef79a4e76373756a3b255
  spot-ros:
    type: git
    url: https://github.com/sktometometo/spot_ros.git
    version: 21c2e0bd7384abb70b16745e011af7ce45281899
  tork-a/roswww:
    type: git
    url: https://github.com/knorth55/roswww.git
    version: fcb215a9331a7ac4086e7b63df9ddd6cac3fdd50
  tork-a/visualization_rwt:
    type: git
    url: https://github.com/tork-a/visualization_rwt.git
    version: 9c015164e95ec13492dac9bf433c082355168ce4
```
