### ISSUE TITLE
Error messages from rviz plugin if slightly different timestamps on jsk_recognition_msgs::BoundingBox and jsk_recognition_msgs::BoundingBoxArray

### ISSUE THREAD

**Issue by LukeAI** [jsk-ros-pkg/jsk_recognition#2693]
when visualising `jsk_recognition_msgs::BoundingBoxArray` messages in rviz I get a continuous stream of errors like:
```
[ERROR] [1653988934.211462038, 1653039959.620125962]: Error transforming pose from frame 'robosense' to frame 'odom'
```
I am running with `use_sim_time` set to true but for some reason the error is referring to the simtime header timestamp and walltime. but there is not problem if I check the transform with `tf_echo` etc.  The box actually displays fine, as expected, but the stream of errors and "status:error " isn't nice. After some experimentation, I found that this error is triggered if there is a small time difference between the BoundingBoxArray header and the BoundingBox header. - IMO this shouldn't cause error messages (with misleading timestamp information) - If the headers are required to match, why give BoundingBox it's own header at all? 

Example of a message that triggers this error:
```
header:
  seq: 115
  stamp:
    secs: 1653039960
    nsecs: 272659712
  frame_id: "robosense"
boxes:
  -
    header:
      seq: 1790
      stamp:
        secs: 1653039960
        nsecs: 303273000
      frame_id: "robosense"
    pose:
      position:
        x: 1.36299991608
        y: -5.19791555405
        z: -44.6151123047
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
    dimensions:
      x: 8.6210603714
      y: 2.19007778168
      z: 3.11404800415
    value: 0.0
    label: 0
```

Example of message that does not trigger this error:

```
header:
  seq: 128
  stamp:
    secs: 1653039962
    nsecs: 203193000
  frame_id: "odom"
boxes:
  -
    header:
      seq: 1809
      stamp:
        secs: 1653039962
        nsecs: 203193000
      frame_id: "odom"
    pose:
      position:
        x: 27.8320557452
        y: 32.1484681139
        z: 3.56229163106
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
    dimensions:
      x: 8.55009746552
      y: 2.14910793304
      z: 2.73072433472
    value: 0.0
    label: 0
```

I am on ubuntu 18.04 using:
```
$ apt show ros-melodic-jsk-recognition-msgs
Package: ros-melodic-jsk-recognition-msgs
Version: 1.2.15-1bionic.20220127.163829
Priority: optional
Section: misc
Maintainer: Ryohei Ueda <ueda@jsk.t.u-tokyo.ac.jp>
Installed-Size: 8278 kB
Depends: ros-melodic-geometry-msgs, ros-melodic-jsk-footstep-msgs, ros-melodic-message-generation, ros-melodic-pcl-msgs, ros-melodic-sensor-msgs, ros-melodic-std-msgs
Homepage: https://jsk-docs.readthedocs.io/projects/jsk_recognition/en/latest/jsk_recognition_msgs
Download-Size: 778 kB
APT-Manual-Installed: yes
APT-Sources: http://packages.ros.org/ros/ubuntu bionic/main amd64 Packages
Description: ROS messages for jsk_pcl_ros and jsk_perception.
```
