### ISSUE TITLE
resize_points_publisher publishes wrong timestamp

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_recognition#698]
A lot of messages have the same timestamp

```
jskuser@fuji:~$ rostopic echo /multisense/resize_1_8/points/header
seq: 334
stamp: 
  secs: 1423807604
  nsecs: 202330000
frame_id: /left_camera_optical_frame
---
seq: 335
stamp: 
  secs: 1423807604
  nsecs: 202330000
frame_id: /left_camera_optical_frame
---
seq: 336
stamp: 
  secs: 1423807604
  nsecs: 202330000
frame_id: /left_camera_optical_frame
---
seq: 337
stamp: 
  secs: 1423807604
  nsecs: 202330000
frame_id: /left_camera_optical_frame
---
seq: 338
stamp: 
  secs: 1423807604
  nsecs: 602331000
frame_id: /left_camera_optical_frame
---
seq: 339
stamp: 
  secs: 1423807604
  nsecs: 602331000
frame_id: /left_camera_optical_frame

```
